# 🛠 00. TensorFlow Fundamentals Exercises


## TensorFlow Basics

In [84]:
import tensorflow as tf

Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [85]:
# Scalar
scalar = tf.constant(6)

# Vector
vector = tf.constant([2,4,3,5,6,3])

# Matrix
matrix = tf.constant([[2,3,4],
                      [8,6,7],
                      [9,0,8]])

# Tensor
tensor = tf.constant([[[1,2,3,4],
                       [2,3,4,5]],
                      [[4,5,6,7],
                       [4,2,5,6]],
                      [[7,4,6,8],
                       [1,5,2,0]]])

Find the shape, rank and size of the tensors you created in 1.

In [7]:
# Find the shape of the tensors
print(f'The shapes of the tensors are:\nScalar : {scalar.shape}\nVector: {vector.shape}\nMatrix : {matrix.shape}\nTensor : {tensor.shape}')

# Rank of the tensors
print(f'\nThe rank of the tensors are:\nScalar : {tf.rank(scalar)}\nVector: {tf.rank(vector)}\nMatrix : {tf.rank(matrix)}\nTensor : {tf.rank(tensor)}')

# Size of the tensors
print(f'\nThe sizes of the tensors are:\nScalar : {tf.size(scalar)}\nVector: {tf.size(vector)}\nMatrix : {tf.size(matrix)}\nTensor : {tf.size(tensor)}')

The shapes of the tensors are:
Scalar : ()
Vector: (6,)
Matrix : (3, 3)
Tensor : (3, 2, 4)

The rank of the tensors are:
Scalar : 0
Vector: 1
Matrix : 2
Tensor : 3

The sizes of the tensors are:
Scalar : 1
Vector: 6
Matrix : 9
Tensor : 24


Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [27]:
# Creating random tensors
tensor_1 = tf.random.normal(shape = (5, 300))
tensor_2 = tf.random.normal(shape = (5, 300))

Multiply the two tensors you created in 3 using matrix multiplication.


In [29]:
# Element wise multiplication tensor_1 * tensor_2
tensor_mul = tf.matmul(tensor_1, tf.transpose(tensor_2))
tensor_mul

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-10.74868   ,  36.950775  ,  -2.1166086 ,  -6.9507236 ,
          0.65623534],
       [ -8.491055  ,   2.3131905 ,  -2.6054068 , -66.92413   ,
        -24.704407  ],
       [-13.600807  ,  30.676186  ,   1.3501587 ,  -8.142902  ,
         16.665956  ],
       [-21.648539  ,   4.057351  ,  28.068123  , -17.40723   ,
        -10.448854  ],
       [ 21.12691   ,  -6.2340403 , -22.58874   , -19.205116  ,
         -7.462863  ]], dtype=float32)>

In [30]:
tensor_1 * tensor_2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[ 0.18749152, -0.10036606,  0.35024667, ...,  0.6744815 ,
        -0.28920147,  1.4078763 ],
       [ 0.21769829, -0.36752704,  0.79440415, ..., -0.0088661 ,
        -0.32589558,  0.40568423],
       [-1.6344783 ,  0.00905384, -0.01382188, ..., -0.01822623,
         1.0463705 ,  0.06886312],
       [ 0.13679513,  0.62685436,  0.40511543, ..., -0.2739662 ,
        -3.752052  , -0.72338235],
       [ 1.9322603 , -0.08500735, -1.6532104 , ...,  0.59749514,
        -0.19547603,  0.3120495 ]], dtype=float32)>

Multiply the two tensors you created in 3 using dot product.

In [33]:
# The dot product
tf.tensordot(tensor_1, tf.transpose(tensor_2), axes = 1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-10.74868   ,  36.950775  ,  -2.1166086 ,  -6.9507236 ,
          0.65623534],
       [ -8.491055  ,   2.3131905 ,  -2.6054068 , -66.92413   ,
        -24.704407  ],
       [-13.600807  ,  30.676186  ,   1.3501587 ,  -8.142902  ,
         16.665956  ],
       [-21.648539  ,   4.057351  ,  28.068123  , -17.40723   ,
        -10.448854  ],
       [ 21.12691   ,  -6.2340403 , -22.58874   , -19.205116  ,
         -7.462863  ]], dtype=float32)>

In [38]:
# A @ B
tensor_1 @ tf.transpose(tensor_2)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-10.74868   ,  36.950775  ,  -2.1166086 ,  -6.9507236 ,
          0.65623534],
       [ -8.491055  ,   2.3131905 ,  -2.6054068 , -66.92413   ,
        -24.704407  ],
       [-13.600807  ,  30.676186  ,   1.3501587 ,  -8.142902  ,
         16.665956  ],
       [-21.648539  ,   4.057351  ,  28.068123  , -17.40723   ,
        -10.448854  ],
       [ 21.12691   ,  -6.2340403 , -22.58874   , -19.205116  ,
         -7.462863  ]], dtype=float32)>

Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [39]:
# Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
tensor_3 = tf.random.normal(shape = (224, 224, 3))
tensor_3.shape

TensorShape([224, 224, 3])

Find the min and max values of the tensor you created in 6 along the first axis.

In [45]:
# Find the min and max values of the tensor along the first axis.
min_values = tf.reduce_min(tensor_3, axis = 0)
max_values = tf.reduce_max(tensor_3, axis = 0)
print(f"Min values:\n{min_values}")
print(f"\n\nMax values:\n{max_values}")

Min values:
[[-2.9375727 -2.6746614 -2.3803856]
 [-2.4781744 -2.6238844 -2.8068242]
 [-2.4018087 -2.833213  -2.3339512]
 [-2.348907  -3.1779459 -2.6972742]
 [-4.266416  -3.5050566 -3.391056 ]
 [-3.1331518 -2.5319357 -2.5436234]
 [-2.6763363 -2.7991111 -3.1606503]
 [-3.3121068 -3.2418127 -2.5758495]
 [-2.2606328 -3.1178696 -2.9870594]
 [-2.8378096 -2.628743  -2.5208166]
 [-2.8617818 -2.8553066 -2.3829618]
 [-3.5176775 -3.042174  -2.3079252]
 [-3.0346565 -2.8813396 -2.0779612]
 [-2.2604198 -2.6023922 -3.1414385]
 [-3.0475705 -3.4530673 -2.5490174]
 [-2.6380932 -2.3961468 -3.1605527]
 [-2.6524367 -3.2357779 -2.5715356]
 [-3.1997552 -2.8524969 -2.5054715]
 [-3.2648957 -2.601147  -3.0574086]
 [-3.8953397 -3.3747773 -3.4208872]
 [-2.4274743 -2.3200727 -3.8684297]
 [-2.7735302 -3.9205122 -2.5894313]
 [-2.8734143 -2.7211235 -2.5346246]
 [-2.9282916 -2.881946  -2.662217 ]
 [-2.2102876 -3.3801792 -2.749961 ]
 [-2.6687424 -2.988495  -2.6916559]
 [-2.7646706 -2.7453184 -2.720529 ]
 [-2.2584343 -2.

Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [47]:
# Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
tensor_4 = tf.random.normal(shape = (1, 224, 224, 3))
print(f"Tensor shape before squeezing: {tensor_4.shape}")
print(f"Tensor shape after squeezing: {tf.squeeze(tensor_4).shape}")

Tensor shape before squeezing: (1, 224, 224, 3)
Tensor shape after squeezing: (224, 224, 3)


In [81]:
# Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
tensor_5 = tf.constant([np.random.randint(10, 100) for _ in range(10)])
print(f"Tensor of shape (10):\n{tensor_5}")
max = tf.argmax(tensor_5).numpy()
print(f"\nThe index having the max value: {max}\nAnd the max value is : {tensor_5[max].numpy()}")

Tensor of shape (10):
[96 46 24 25 56 78 83 39 30 81]

The index having the max value: 0
And the max value is : 96


One-hot encode the tensor you created in 9.

In [83]:
# one hot encode the tensor
tensor_5_one_hot = tf.one_hot(tensor_5, depth = tf.reduce_max(tensor_5))
tensor_5_one_hot

<tf.Tensor: shape=(10, 96), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 