# 00. ZTM_PyTorch Fundamentals

## `What is PyTorch`?


1. It is the most popular research deep learning framework.

2. It helps you write fast deep learning code in python.

3. Able to access many prebuilt deep leaqrning models.

4. Whoile stack: Preprocess data, model data, deploy model in your application/cloud

5. It is now open source.

In [3]:
import torch
import numpy as np
import pandas as pd
import matplotlib as plt
print(torch.__version__)

2.2.1+cu121


## Introduction to Tensors

### Creating Tensors

In [4]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.shape

torch.Size([])

In [7]:
# Get tensor back as Python int
scalar.item()

7

Think of torch.Tensor() as creating an empty container. It allocates memory for a tensor but doesn't initialize the values inside. It's like having a box with nothing inside it yet. You have the box, but you haven't put anything in it.

**Function Purpose:**

* **torch.Tensor():** This is a constructor function used to create an empty tensor in PyTorch. It doesn't take any arguments and initializes a tensor with an undefined data type and size. You typically wouldn't use this directly in practice.

* **torch.tensor():** This is a more flexible function used to create a tensor from various data sources. It takes different arguments to specify the data, data type, and device (CPU or GPU).

In [8]:
# Vector
vector = torch.tensor([1,2])
vector

tensor([1, 2])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

By using uppercase for class names like Tensor and Matrix, PyTorch follows this convention and makes it clear that these are class types representing multidimensional arrays and matrices, respectively. It helps improve code readability and maintainability by making it easier to identify data types and distinguish them from other entities in the code.

In [11]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX[1][1]

tensor(10)

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 4, 5],
                        [2, 5, 8]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [2, 5, 8]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [2, 5, 8]])

In [19]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 4, 5],
                        [2, 5, 8]],

                       [[2, 3, 4],
                        [2, 3, 4],
                        [8, 9, 0]],

                       [[1, 2, 5],
                        [3, 4, 8],
                        [5, 6, 7]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [2, 5, 8]],

        [[2, 3, 4],
         [2, 3, 4],
         [8, 9, 0]],

        [[1, 2, 5],
         [3, 4, 8],
         [5, 6, 7]]])

In [20]:
TENSOR.ndim

3

In [21]:
TENSOR.shape

torch.Size([3, 3, 3])

### Random Tensors

Why Random Tensors?

Random tensors are important because the way many neural networks learn is that they start tensors with full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> Look at data -> update random numbers -> look at data -> update random numbers`


In [22]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2987, 0.0197, 0.5577, 0.5165],
        [0.6355, 0.8922, 0.4281, 0.3819],
        [0.2317, 0.6046, 0.6424, 0.6530]])

In [23]:
random_tensor.ndim

2

In [24]:
# Create a random tensor wiht similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (224, 224, 3)) # Height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeroes and Ones

In [25]:
# Create a tensor of all zeroes
zeros = torch.zeros(size = (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
# Create a tensor of all ones
ones = torch.ones(size = (3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
ones.dtype

torch.float32

In [28]:
TENSOR.dtype

torch.int64

### Create a range of tensors and tensors-like

In [29]:
# Use torch.arange
one_to_ten = torch.arange(start = 1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
# Creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**Note:** Tensor Datatypes is one of the 3 big errors you'll run into wiht PyTorch & deep learning.

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [31]:
# Float32 tensor (default type)
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # What datatype is the tensor?
                               device = None, # What device is your tensor on
                               requires_grad = False) # Whether or not to track gradients with this tensors operations
float_32_tensor.dtype

torch.float32

Float16 and Float32 are the most common types of tensors that we will come across. They have a thing about precision in computing i.e., How much detail a single number is stored in memory.

In [32]:
# Float32 tensor (default type)
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = torch.float16, # What datatype is the tensor?
                               device = None, # What device is your tensor on
                               requires_grad = False) # Whether or not to track gradients with this tensors operations

# OR another way
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [33]:
# Caveat(warning) in pytorch
result = float_16_tensor * float_32_tensor
result.dtype

torch.float32

In [34]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [35]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [36]:
int_64_tensor = torch.tensor([3, 6, 9], dtype = torch.int64)
int_64_tensor

tensor([3, 6, 9])

In [37]:
float_32_tensor * int_64_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

1. Tensors not right datatype - To do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use tensor.shape
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`


In [38]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5246, 0.8500, 0.7675, 0.5239],
        [0.7551, 0.3131, 0.8010, 0.8644],
        [0.7515, 0.2088, 0.9195, 0.1727]])

In [39]:
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [40]:
# Find out details about some tensor
print(some_tensor)
print(f'\nDatatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is on: {some_tensor.device} ')

tensor([[0.5246, 0.8500, 0.7675, 0.5239],
        [0.7551, 0.3131, 0.8010, 0.8644],
        [0.7515, 0.2088, 0.9195, 0.1727]])

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu 


### Manipulating tensors (tensor operations)

Tensor operations include:
1. Addition
2. Subtraction
3. Multiplication (element-wise)
4. Division
5. Matrix Multiplication

In [41]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [42]:
# Add 10 to the tensor
tensor + 10

tensor([11, 12, 13])

In [43]:
# Multiply the tensor by 10
tensor * 10

tensor([10, 20, 30])

In [44]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [45]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [46]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix Multiplication (dot-product : `"."`)


More info on matrix multiplication: [click here](https://www.mathsisfun.com/algebra/matrix-multiplying.html)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions:**
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [47]:
# Element-wise multiplcation
print(tensor, '*', tensor)
print(f'Equals: {tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [48]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [49]:
# Matrix multiplication by hand
1 * 1 + 2 * 2 + 3 * 3

14

In [51]:
%%time
value = 0
for i in range(len(tensor)):
  value +=  tensor[i] * tensor[i]

print(value)

tensor(14)
CPU times: user 4.37 ms, sys: 0 ns, total: 4.37 ms
Wall time: 7.62 ms


In [52]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 522 µs, sys: 0 ns, total: 522 µs
Wall time: 446 µs


tensor(14)

### One of the common errors in deep learning: shape errors

In [57]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

#torch.mm(tensor_A, tensor_B) # Torch.mm is same as torch.matmul (It's an alias for writing less code)
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using **transpose**

A **transpose** switches the axes or dimensions of a given tensor.

In [58]:
tensor_B.T, tensor_B

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

In [63]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B: {tensor_B.shape}")
print(f"New Shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying : {tensor_A.shape} @ {tensor_B.T.shape}")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B: torch.Size([3, 2])
New Shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying : torch.Size([3, 2]) @ torch.Size([2, 3])
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum, etc (tesnor aggregation)

In [65]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [67]:
# Find the min()
torch.min(x), x.min()

(tensor(0), tensor(0))

In [69]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [78]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [79]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [81]:
# Find the index position of the min and max values
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [83]:
# Find the index of the max value
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

### Reshaping, stacking, squeezing and unsqueezing

* Reshaping: Reshapes an input tensor to a defined shape
* View: Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking: combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze: removes all `1` dimensions from a tensor
* Unsqueeze: add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permutes (swapped) in a certain way

In [2]:
# Let's create a tensor
import torch
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [12]:
# Add an extra dimension
x_reshaped = x.reshape(1, 10)
x_reshaped, x_reshaped.shape

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [4]:
# Change the view z shares the same memory as x
z = x.view(1, 10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

changing z changes x (because a view of a tensor shares the same memory as the original input)

In [5]:
# Lets try changing the first element of z and see how x changes
z[:, 0] = 5
x, z

(tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]))

In [6]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [16]:
# torch.squeeze() removes the input dimensions from a target tensor
print(f'Previous tensor: {x_reshaped}')
print(f'Previous shape: {x_reshaped.shape}')

# Remove extra dimensions from x_shaped
x_squeezed = x_reshaped.squeeze()
print(f'\nNew tensor: {x_squeezed}')
print(f'New shape: {x_squeezed.shape}')

Previous tensor: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
Previous shape: torch.Size([1, 10])

New tensor: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
New shape: torch.Size([10])


In [17]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
# torch.squeeze() removes the input dimensions from a target tensor
print(f'Previous target: {x_squeezed}')
print(f'Previous shape: {x_squeezed.shape}')

# Add an extra dimension with unsqueeze
x_usqueezed = x_squeezed.unsqueeze(dim = 0)
print(f'\nNew tensor: {x_usqueezed}')
print(f'New shape: {x_usqueezed.shape}')

Previous target: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
Previous shape: torch.Size([10])

New tensor: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
New shape: torch.Size([1, 10])


Returns a view of the original tensor input with its dimensions permuted.
The common places where you will beusing permute is with image tensors.

In [18]:
# torch.permute - rearranges the dimensions of a target tensor into specified order
x_original = torch.rand(size = (224, 224, 3)) # [height, width, color_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # Shift axis 0 -> 1, 1 -> 2, 2 -> 0

print(f'Previous shape: {x_original.shape}')
print(f'New shape: {x_permuted.shape}') # [color_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [22]:
# Changing the value of xoriginal will make the change to x_permuted
x_original[0,0,0] = 9123

In [21]:
x_permuted[0,0,0]

tensor(9123.)

### Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with numpy

In [24]:
# Create the tensor
import torch

x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [25]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [26]:
# Lets index on the middle bracket (dim = 1)
x[0][0]

tensor([1, 2, 3])

In [27]:
# Let's index on the most inner brack (last dimension)
x[0][0][0]

tensor(1)

In [30]:
x[0][2][2].item()

9

In [31]:
# Get all values of 0th and 1st dimension but only index 1 of the 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [35]:
# Get all values of 0th dimension but only index 1 of 1st and 2nd dimension
x[0, 1, 1]

tensor(5)

In [37]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension\
x[0, 0, :]

tensor([1, 2, 3])

In [40]:
# index on x to return 3,6,9
x[:, :, 2]

tensor([[3, 6, 9]])

## PyTorch Tensors & NumPy

Numpy is a popular scientific python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.Numpy()`

In [44]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
# Converting numpy array to pytorch tensor
tensor = torch.from_numpy(array) # warning: When converting from numpy -> pytorch reflects numpy's default dtaatype of float64 unless specified otherwise: numpy datatype is float64 and for pytorch it is float32
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [43]:
# Change the value of aray, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [45]:
# Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [46]:
numpy_tensor.dtype

dtype('float32')

In [48]:
# Change the tensor, what happens to `numpy_tensor`? It doesn't changes
tensor = tensor + 1
tensor, numpy_tensor

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (Trying to take random out of random)

In short how a neural network learns is:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of teh data -> again -> again -> again..`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is "flavour" the randomness.

[check out for more](https://pytorch.org/docs/stable/notes/randomness.html)

In [54]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print('\n',random_tensor_A == random_tensor_B)

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753],
        [0.8860, 0.5832, 0.3376, 0.8090]])

 tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [55]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print('\n',random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

 tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running Tensors and PyTorch objects on the GPU's (and making faster computations)

GPU's = faster compuation on numbers, thanks to CUDE + NVIDIA hardware + PyTorch working behind the scenes to make everday hunky dory (good).

### 1. Getting a GPU

1. Easiest : Use google colab for free GPU
2. Use your own GPU -  takes a little bit of setup and investment for getting a GPU.
3. Use cloud computing such as GCP, AWS, Azure: Allows you to rent computers on the cloud and access them.

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up.

In [1]:
!nvidia-smi

Thu Apr 18 17:05:21 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   46C    P8              12W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

## Check for GPU access with PyTorch

For PyTorch since it's capable of running the compute on the GPU or CPU, it's best practice to setup device agnostic code:
https://pytorch.org/docs/stable/notes/cuda.html#best-practices

In [3]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [6]:
# Setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [7]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting Tensors and Models on GPU

The reason we want our tensors/models on the GPU is because GPU results in faster tensor operations.

In [8]:
# Create a tensor (default on CPU)
tensor = torch.tensor([1, 2, 3], device = 'cpu')

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [10]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU


In [11]:
# If tensor is on GPU, can;t transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [12]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [13]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')