In [1]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [7]:
# Define the vocab size
vocab_size = 10000


In [8]:
# ONe hot representation 
one_hot_repr = [one_hot(words, vocab_size) for words in sent]
one_hot_repr

[[3295, 4744, 2378, 5369],
 [3295, 4744, 2378, 9193],
 [3295, 5652, 2378, 7240],
 [3881, 6659, 1673, 2812, 1784],
 [3881, 6659, 1673, 2812, 5015],
 [8504, 3295, 4150, 2378, 6423],
 [7840, 1833, 5678, 2812]]

In [13]:
## Word embedding representation
from tensorflow.keras.layers import Embedding
#from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences
import numpy as np

In [14]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding = 'pre', maxlen=sent_length)
embedded_docs

array([[   0,    0,    0,    0, 3295, 4744, 2378, 5369],
       [   0,    0,    0,    0, 3295, 4744, 2378, 9193],
       [   0,    0,    0,    0, 3295, 5652, 2378, 7240],
       [   0,    0,    0, 3881, 6659, 1673, 2812, 1784],
       [   0,    0,    0, 3881, 6659, 1673, 2812, 5015],
       [   0,    0,    0, 8504, 3295, 4150, 2378, 6423],
       [   0,    0,    0,    0, 7840, 1833, 5678, 2812]], dtype=int32)

In [27]:
# Fetaure representations
dim = 10

model = Sequential()
model.add(Embedding(input_dim = vocab_size, output_dim = dim))
model.compile('adam', 'mse')


In [30]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (7, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [42]:
prediction = model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 522ms/step


In [38]:
embedded_docs[0].astype(np.float32)

array([   0.,    0.,    0.,    0., 3295., 4744., 2378., 5369.],
      dtype=float32)

In [43]:
prediction.shape

(7, 8, 10)

In [46]:
pred = model.predict(np.expand_dims(embedded_docs[0], axis=0))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step


In [47]:
pred.shape

(1, 8, 10)

In [48]:
pred

array([[[ 0.04444125,  0.04421541,  0.02573032,  0.01287341,
         -0.02264291, -0.04289005, -0.04165038, -0.03530926,
         -0.00213963, -0.03229237],
        [ 0.04444125,  0.04421541,  0.02573032,  0.01287341,
         -0.02264291, -0.04289005, -0.04165038, -0.03530926,
         -0.00213963, -0.03229237],
        [ 0.04444125,  0.04421541,  0.02573032,  0.01287341,
         -0.02264291, -0.04289005, -0.04165038, -0.03530926,
         -0.00213963, -0.03229237],
        [ 0.04444125,  0.04421541,  0.02573032,  0.01287341,
         -0.02264291, -0.04289005, -0.04165038, -0.03530926,
         -0.00213963, -0.03229237],
        [ 0.04770771, -0.03967639, -0.04798782,  0.03276184,
          0.04541877,  0.00892479, -0.00380572,  0.04631758,
         -0.03439689, -0.00275136],
        [ 0.01486515, -0.04361347,  0.0127424 , -0.015337  ,
         -0.01185498,  0.01370684, -0.01111963,  0.00309117,
          0.02353523, -0.04351232],
        [ 0.04417035,  0.03402192, -0.00183647, -0.0